---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  isCA: false
  commonName: {{ .Values.certificate.name }}
  secretName: {{ .Values.certificate.name }}
  subject:
    organizations:
      - "Craig Miller"
    organizationalUnits:
      - Postgres
    countries:
      - US
  dnsNames:
    - {{ .Values.deployment.name }}
    - "{{ .Values.deployment.name }}.{{ .Release.Namespace }}"
    - {{ .Values.lan_host }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: craigmiller160-selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io